FROM quay.io/fedora/fedora-toolbox:40

# Support Nvidia Container Runtime (https://developer.nvidia.com/nvidia-container-runtime)
# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES all

LABEL com.github.containers.toolbox="true" \
    usage="This image is meant to be used with the toolbox or distrobox commands" \
    summary="Citrix Workspace App" \
    maintainer="karypid@gmail.com"

RUN mkdir /container && chmod a+rx /container
COPY container /container
RUN chmod a+rx /container/download-icaclient.sh
RUN dnf -y update && \
    grep -v '^#' /container/extra-packages | xargs dnf -y install

WORKDIR /container
RUN /container/download-icaclient.sh && dnf install -y /container/ICAClient-rhel-*.rpm

