FROM quay.io/fedora/fedora-toolbox:43

# Support Nvidia Container Runtime (https://developer.nvidia.com/nvidia-container-runtime)
# ENV NVIDIA_VISIBLE_DEVICES all
# ENV NVIDIA_DRIVER_CAPABILITIES all

COPY container /container
RUN dnf -y update && \
    grep -v '^#' /container/extra-packages | xargs dnf -y install
RUN rm /container/extra-packages

# Download installers
WORKDIR /container
RUN chmod a+rx /container/download-ib-tws.sh
RUN /container/download-ib-tws.sh stable
RUN /container/download-ib-tws.sh latest

