FROM quay.io/toolbx/ubuntu-toolbox:24.04

# Ubuntu packages
COPY container /container
RUN apt-get update && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    $(cat /container/packages.ubuntu | xargs)
RUN rm -rd /var/lib/apt/lists/* && \
    rm /container/packages.ubuntu && \
    true

