FROM quay.io/toolbx/ubuntu-toolbox:24.04

LABEL com.github.containers.toolbox="true" \
    name="tbox-dev-java" \
    usage="This image is meant to be used with the toolbox or distrobox command" \
    summary="A cloud-native terminal experience powered by Ubuntu" \
    maintainer="karypid@gmail.com"

# Ubuntu packages
COPY container /container
RUN apt-get update && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    $(cat /container/packages.ubuntu | xargs)
RUN rm -rd /var/lib/apt/lists/* && \
    rm /container/packages.ubuntu && \
    true

# Install Eclipse
RUN mkdir -p /oomph
WORKDIR /oomph
# Download OOMPH CONSOLE INSTALLER - see: https://github.com/a-langer/eclipse-oomph-console
RUN mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:unpack \
    -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:tar.gz:linux.gtk.x86_64 \
    -DoutputDirectory=./ -Dproject.basedir=./
RUN ./eclipse-installer/eclipse-inst -nosplash -application org.eclipse.oomph.console.application -vmargs \
    -Doomph.installer.layout="text" \
    -Doomph.installation.location="/opt/" \
    -Doomph.workspace.location="/oomph/inst-ws" \
    -Doomph.redirection.setupsDir="index:/->/container/alxclipse/" \
    -Doomph.product.id="alxclipse:2024-09"

# Prepare for SDKman (needs to be installed on entry)
RUN mkdir -p /opt/sdk
RUN chmod a+rx /container/configure-container.sh

